import = ["~/.config/alacritty/themes/themes/catppuccin_frappe.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"
opacity = 0.85
blur = true


[font]
size = 16
normal.family = "GeistMono Nerd Font Mono"
